### PR TITLE
Tweaks based on "reliable" plugin experience

### PR DESCRIPTION
**Pull request by philippe44**
A few tweaks if you want to on the "persistent" HTTP implementation. The issues I've seen on the "reliable" plugin and applied here are probably not an issue for RP because it's a continuous stream, but that's cleaner like that

### CODE REVIEW

**Comment by michaelherger** [comment]
Thanks, will give that a try!

**Comment by michaelherger** [comment]
Hey @philippe44 - I just realized that while I merged this PR, I never used, nor released it... is this still a valid change with the more recent improvements you did in LMS 8.2?

**Comment by philippe44** [comment]
Yes it is because RP has its own sysread, so it does not benefit from built-in changes

**Comment by michaelherger** [comment]
Thanks!

**Pull request merged**
